### PR TITLE
Alison Callahan @Stanford integration guide addition

### PR DESCRIPTION
**Pull request by alisoncallahan**
# Overview
Updating Integration Guide doc to add link to APLUSML notebook that uses seismometer data format 
## Description of changes
Edited seismometer/docs/integration_guide/index.rst to add a table where other packages that integrate with seismometer can be linked.

### CODE REVIEW

**Comment by firste** [comment]
Can you also add a changelog fragment so this feature is attributed in the release notes for the next version? [This readme](https://github.com/epic-open-source/seismometer/blob/main/changelog/README.rst) has directions and [this directory](https://github.com/epic-open-source/seismometer/tree/main/changelog) is where you will put the fragment. I think you can either flag this as a doc change or a feature.

**Comment by firste** [comment]
Can you use this use this for the integration.rst file? I want to add subsections to this guide.
```
.. _integration_guide:

=================
Integration Guide
=================

This guide contains references to systems and packages that integrate with Seismometer. If you are interested in including your content here, either open a pull request or reach out to OpenSourceContributions-Python@epic.com

Vendor Specific Resources
=========================

Your model developer or health IT vendor might provide guidance on how to extract data from your system for use in ``seismometer``. The following table provides links to vendor specific integration instructions. Note that some links might only be accessible if you are licensed with the 
associated vendor.

+----------------------------+-----------------------------------------------+
| Vendor                     | Integration instructions                      |
+============================+===============================================+
| Epic                       | `Setup and Support Guide`_                    |
+----------------------------+-----------------------------------------------+

.. _Setup and Support Guide: https://galaxy.epic.com/Redirect.aspx?DocumentID=100277113        

Seismometer Community
=====================

You might also be interested in using ``seismometer`` with other open source tools that assess complementary facets of AI systems deployed in specific settings. The following table provides a list of such 
tools and links to relevant code/documentation.

+----------------------------+----------------------------------------------------------+---------------------------------------------+
| Package name               | Description                                              | Link                                        |
+============================+==========================================================+=============================================+
| APLUSML                    | A Python Library for Usefulness Simulations of ML Models | `Example notebook integrating seismometer`_ |
+----------------------------+----------------------------------------------------------+---------------------------------------------+

.. _Example notebook integrating seismometer: https://github.com/som-shahlab/aplusml/blob/seismometer_integration/tutorials/synthetic_pad_seismometer.ipynb

```

**Review by firste — CHANGES_REQUESTED** [review]
See the other two comments for items to address

**Comment by alisoncallahan** [comment]
@firste committed the requested changes!

**Review by firste — APPROVED** [review]

**Pull request merged**
